apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-nginx-nlb
  name: my-nginx-nlb
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx-nlb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx-nlb
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: my-nginx-nlb
